-- RedZone Companion Supabase schema
-- Run in the Supabase SQL editor for each environment.

create table if not exists public.user_leagues (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sleeper_league_id text not null check (sleeper_league_id ~ '^[0-9]+$'),
  sleeper_user_id text,
  league_name text,
  custom_nickname text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, sleeper_league_id)
);

create index if not exists user_leagues_user_id_idx
  on public.user_leagues (user_id);

alter table public.user_leagues enable row level security;

drop policy if exists "Users can view their own leagues" on public.user_leagues;
create policy "Users can view their own leagues"
  on public.user_leagues
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert their own leagues" on public.user_leagues;
create policy "Users can insert their own leagues"
  on public.user_leagues
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their own leagues" on public.user_leagues;
create policy "Users can update their own leagues"
  on public.user_leagues
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own leagues" on public.user_leagues;
create policy "Users can delete their own leagues"
  on public.user_leagues
  for delete
  using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists user_leagues_set_updated_at on public.user_leagues;
create trigger user_leagues_set_updated_at
  before update on public.user_leagues
  for each row
  execute function public.set_updated_at();
